### ISSUE TITLE
Add missing parts of the java client api

### ISSUE THREAD

**Issue by Spacemetric-Oscar** [eoport/platform-samples#1]
If you want to simplify even more for integrators of the EOPORT API, i would suggest adding the missing parts of the Java API.
Currently the provided code does not compile because it references classes 
```
import com.geocento.projects.eoport.api.*;
import com.geocento.projects.eoport.utils.ApiClient;
``` 
that are not provided as source code nor as dependencies in any of the pom files.

**Comment by leforthomas** [comment]
Thanks for this. Normally the missing files should be generated automatically with Maven, please have a look at the pom, the swagger-codegen-maven-plugin is used to generate the missing Java files. You can trigger it by running a compile. Let me know if this is not working for you.

**Comment by Spacemetric-Oscar** [comment]
I am unable to run `mvn clean install` as I get the following exception

```
[ERROR] unable to read
java.net.UnknownHostException: webapp.dev02.eoport.eu
    at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:220)
```

**Comment by leforthomas** [comment]
It looks like the latest commit hadn't been pushed to GitHub, the api end point has changed since then, hence the failure. Please pull the new commit and let me know if it works for you now.

**Comment by Spacemetric-Oscar** [comment]
```
[ERROR]
[ERROR]   The project com.geocento.projects.eoport:APIClientExample:1.0-SNAPSHOT (C:\dev\source\eoport-samples\JavaExamples\APIClientExample\pom.xml) has 1 error
[ERROR]     Invalid packaging for parent POM com.geocento.projects.eoport:ServiceExample:1.0-SNAPSHOT (C:\dev\source\eoport-samples\JavaExamples\ServiceExample\pom.xml), must be "pom" but is "war" @ com.geocento.projects.eoport:ServiceExample:1.0-SNAPSHOT, C:\dev\source\eoport-samples\JavaExamples\ServiceExample\pom.xml, line 13, column 16
```
This is if I run mvn in the APIClientExample folder.
If I run in the parent folder, it will not build the client.

**Comment by leforthomas** [comment]
Sorry, there was some wrong configurations indeed. I updated the POMs now, cleaned and regenerated everything and it works for me. Can you pull the new commit, try again please and let me know?

**Comment by Spacemetric-Oscar** [comment]
Yea, now it can be built
